import type { RunSummary } from "./types";
import { ITEM_LABELS } from "./types";

/**
 * Render probe/football/phase0-status.md — the human-readable Phase 0 status.
 * Regenerated (overwritten) on every run; the immutable evidence lives in the
 * per-run directories the table links to.
 */
export function renderStatusReport(summary: RunSummary, notes: string[]): string {
  const lines: string[] = [];
  lines.push("# Phase 0 — Data Proof status");
  lines.push("");
  lines.push("_Generated by `lib/football-probe` from real API responses only._");
  lines.push("_Do not edit by hand — every verdict below links to the captured evidence._");
  lines.push("");
  lines.push(`- Run: \`${summary.runId}\` (${summary.startedAt} → ${summary.finishedAt})`);
  lines.push(
    `- Credentials present: Sportmonks=${summary.credentials.sportmonks ? "yes" : "no"}, ` +
      `The Odds API=${summary.credentials.theOddsApi ? "yes" : "no"}`,
  );
  lines.push("- Reference case: Eredivisie — Cambuur vs Twente (reference match #001)");
  lines.push("");
  lines.push("| # | Item | Verdict | Grounds (from captured responses) | Evidence |");
  lines.push("|---|------|---------|-----------------------------------|----------|");
  summary.verdicts.forEach((v, i) => {
    const evidence =
      v.evidence.length > 0 ? v.evidence.map((e) => `\`runs/${summary.runId}/${e}\``).join(", ") : "—";
    lines.push(`| ${i + 1} | ${ITEM_LABELS[v.item]} | **${v.verdict}** | ${v.reason} | ${evidence} |`);
  });
  lines.push("");
  lines.push("Verdict rules: 2xx with item data → AVAILABLE; 2xx without item data → PARTIAL;");
  lines.push("402/403/404 → UNAVAILABLE (on the current plan); 401 / transport failure /");
  lines.push("not attempted → UNVERIFIED. A verdict is never taken from documentation.");
  if (notes.length > 0) {
    lines.push("");
    lines.push("## Run notes (discovery decisions)");
    lines.push("");
    for (const n of notes) lines.push(`- ${n}`);
  }
  lines.push("");
  return lines.join("\n");
}
