// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/HandiEdgeReport.tsx": () => import("../components/mockups/HandiEdgeReport.tsx"),
  "./components/mockups/HandiEdgeSlate.tsx": () => import("../components/mockups/HandiEdgeSlate.tsx")
};
