/**
 * 公開ページの表示ラベル。**表示だけの読み替えであり、台帳・指紋・確率には影響しない。**
 *
 * `teamNamesJa.ts`（日本語 → 台帳の英語表記）とは向きが逆で、用途も別。
 * あちらは貼り付けられたハンデ表を台帳の試合へ解決するための入力側の表で、
 * 1 つの日本語に複数の綴りが対応しうるため値が配列になっている。
 * こちらは台帳の英語表記を読者向けのカタカナに直すための出力側の表。
 * **片方から他方を機械的に導けない**（短縮形・通称・表記ゆれが非対称）ので 2 枚持つ。
 */

/** 台帳の Division コード → [日本語のリーグ名, 国] */
export const LEAGUE: Readonly<Record<string, readonly [string, string]>> = {
  E0: ["プレミアリーグ", "英"],
  I1: ["セリエA", "伊"],
  SP1: ["ラ・リーガ", "西"],
  D1: ["ブンデスリーガ", "独"],
  N1: ["エールディヴィジ", "蘭"],
  F1: ["リーグ・アン", "仏"],
  P1: ["プリメイラ・リーガ", "葡"],
  B1: ["ベルギー", "白"],
  SC0: ["スコットランド", "蘇"],
  JAP: ["J1", "日"],
};

/**
 * 台帳の英語表記 → カタカナ。
 * **ここに無い名前は推測で埋めず、英語表記のまま出す**（フェイルクローズ）。
 * 未解決は `KanaTable.unmapped` に溜まるので、生成のたびに取りこぼしが見える。
 */
export const EN_TO_KANA: Readonly<Record<string, string>> = {
  Lyon: "リヨン",
  Auxerre: "オセール",
  "Sparta Rotterdam": "スパルタ・ロッテルダム",
  Zwolle: "ズヴォレ",
  Stuttgart: "シュツットガルト",
  "FC Koln": "ケルン",
  Genoa: "ジェノア",
  Como: "コモ",
  Ipswich: "イプスウィッチ",
  Liverpool: "リバプール",
  Betis: "ベティス",
  "Real Madrid": "レアル・マドリード",
  "Paris SG": "パリ・サンジェルマン",
  Monaco: "モナコ",
  Porto: "ポルト",
  Moreirense: "モレイレンセ",
  Newcastle: "ニューカッスル",
  Bournemouth: "ボーンマス",
  Fiorentina: "フィオレンティーナ",
  Torino: "トリノ",
  Leverkusen: "レバークーゼン",
  "Union Berlin": "ウニオン・ベルリン",
  Hoffenheim: "ホッフェンハイム",
  Dortmund: "ドルトムント",
  "Werder Bremen": "ブレーメン",
  "RB Leipzig": "ライプツィヒ",
  Brentford: "ブレントフォード",
  Sunderland: "サンダーランド",
  Brighton: "ブライトン",
  Leeds: "リーズ",
  Fulham: "フラム",
  "Crystal Palace": "クリスタル・パレス",
  "Nott'm Forest": "ノッティンガム・フォレスト",
  Tottenham: "トッテナム",
  Charleroi: "シャルルロワ",
  "St. Gilloise": "ユニオン・サンジロワーズ",
  Aberdeen: "アバディーン",
  Kilmarnock: "キルマーノック",
  "Dundee United": "ダンディー・ユナイテッド",
  Falkirk: "フォルカーク",
  Rangers: "レンジャーズ",
  Motherwell: "マザーウェル",
  "Ath Bilbao": "アスレティック・ビルバオ",
  "Ath Madrid": "アトレティコ・マドリード",
  Nijmegen: "NECナイメヘン",
  Feyenoord: "フェイエノールト",
  Estrela: "エストレラ・アマドーラ",
  Famalicao: "ファマリカン",
  Lens: "ランス",
  Lorient: "ロリアン",
  Inter: "インテル",
  Napoli: "ナポリ",
  Mechelen: "メヘレン",
  Westerlo: "ウェステルロー",
  Utrecht: "ユトレヒト",
  "Go Ahead Eagles": "ゴー・アヘッド・イーグルス",
  Alverca: "アルヴェルカ",
  "Sp Braga": "ブラガ",
  Ajax: "アヤックス",
  "PSV Eindhoven": "PSV",
  Roma: "ローマ",
  Atalanta: "アタランタ",
  "Le Havre": "ル・アーヴル",
  Brest: "ブレスト",
  "St Truiden": "シント＝トロイデン",
  "RAAL La Louviere": "ラ・ルヴィエール",
  Standard: "スタンダール",
  Antwerp: "アントワープ",
  "Willem II": "ヴィレムII",
  Excelsior: "エクセルシオール",
  "St Mirren": "セント・ミレン",
  Celtic: "セルティック",
  "Sp Lisbon": "スポルティング",
  Nacional: "ナシオナル",
  Groningen: "フローニンゲン",
  Twente: "トゥエンテ",
  "Cercle Brugge": "セルクル・ブルッヘ",
  Gent: "ヘント",
  Heerenveen: "ヘーレンフェーン",
  "AZ Alkmaar": "AZアルクマール",
  Everton: "エバートン",
  "Man United": "マンチェスター・U",
  Frosinone: "フロジノーネ",
  Venezia: "ヴェネツィア",
  Parma: "パルマ",
  Monza: "モンツァ",
  Hamburg: "ハンブルガーSV",
  Mainz: "マインツ",
  Kortrijk: "コルトレイク",
  Waregem: "ズルテ・ワレヘム",
  Hearts: "ハーツ",
  Dundee: "ダンディー",
  "St Johnstone": "セント・ジョンストン",
  Hibernian: "ハイバーニアン",
  Valencia: "バレンシア",
  Barcelona: "バルセロナ",
  "Santa Clara": "サンタ・クララ",
  "Rio Ave": "リオ・アヴェ",
  Angers: "アンジェ",
  Rennes: "レンヌ",
  Arsenal: "アーセナル",
  Chelsea: "チェルシー",
  "Ein Frankfurt": "フランクフルト",
  Augsburg: "アウクスブルク",
  Bologna: "ボローニャ",
  Sassuolo: "サッスオーロ",
  Alaves: "アラベス",
  Osasuna: "オサスナ",
  Anderlecht: "アンデルレヒト",
  Genk: "ヘンク",
  Guimaraes: "ギマランイス",
  "Casa Pia": "カーザ・ピア",
  Juventus: "ユベントス",
  Milan: "ミラン",
  Marseille: "マルセイユ",
  "Paris FC": "パリFC",
  Espanol: "エスパニョール",
  Sevilla: "セビージャ",
  Sociedad: "レアル・ソシエダ",
  Celta: "セルタ",
  Toulouse: "トゥールーズ",
  Lille: "リール",
  "Oud-Heverlee Leuven": "OHルーヴェン",
  "Avispa Fukuoka": "福岡",
  Mito: "水戸",
  "Nagoya Grampus": "名古屋",
  Machida: "町田",
  Okayama: "岡山",
  "Sanfrecce Hiroshima": "広島",
  Chiba: "千葉",
  "Gamba Osaka": "G大阪",
  "Kashima Antlers": "鹿島",
  "Urawa Reds": "浦和",
  "Cerezo Osaka": "C大阪",
  Verdy: "東京V",
  "Kashiwa Reysol": "柏",
  "Yokohama F. Marinos": "横浜FM",
  "Kawasaki Frontale": "川崎",
  "Shimizu S-Pulse": "清水",
  "Vissel Kobe": "神戸",
  "V-Varen Nagasaki": "長崎",
  "FC Tokyo": "FC東京",
  Kyoto: "京都",
  "Schalke 04": "シャルケ",
  "Bayern Munich": "バイエルン",
  Freiburg: "フライブルク",
  "M'gladbach": "ボルシアMG",
  Elversberg: "エルフェルスベルク",
  Paderborn: "パーダーボルン",
  "Man City": "マンチェスター・C",
  "Aston Villa": "アストン・ヴィラ",
  Coventry: "コベントリー",
  Hull: "ハル",
  "West Ham": "ウェストハム",
  Wolves: "ウルブス",
  Lazio: "ラツィオ",
  Udinese: "ウディネーゼ",
  Cagliari: "カリアリ",
  Lecce: "レッチェ",
  Getafe: "ヘタフェ",
  Elche: "エルチェ",
  Vallecano: "ラージョ",
  Levante: "レバンテ",
  Villarreal: "ビジャレアル",
  Malaga: "マラガ",
  "La Coruna": "デポルティボ",
  Santander: "ラシン",
  Nice: "ニース",
  Strasbourg: "ストラスブール",
  Troyes: "トロワ",
  "Le Mans": "ル・マン",
  Benfica: "ベンフィカ",
  Estoril: "エストリル",
  Arouca: "アロウカ",
  "Gil Vicente": "ジル・ヴィセンテ",
  "Academico Viseu": "アカデミコ・ヴィゼウ",
  Maritimo: "マリティモ",
  "Club Brugge": "クラブ・ブルッヘ",
  Beveren: "ベフェレン",
  Lommel: "ロンメル",
  "Lommel SK": "ロンメル",
  Telstar: "テルスター",
  Cambuur: "カンブール",
  "Den Haag": "ADOデン・ハーグ",
  "For Sittard": "フォルトゥナ・シッタート",
  Kashiwa: "柏",
  "Machida Zelvia": "町田",
};

export interface KanaTable {
  /** 英語表記をカタカナへ。無ければ英語表記をそのまま返す（推測で埋めない） */
  kana(name: string): string;
  /** 表に無かった名前。生成のたびに報告して取りこぼしを見えるようにする */
  readonly unmapped: Set<string>;
}

export function kanaTable(): KanaTable {
  const unmapped = new Set<string>();
  return {
    kana(name: string): string {
      const hit = EN_TO_KANA[name];
      if (hit !== undefined) return hit;
      if (name) unmapped.add(name);
      return name;
    },
    unmapped,
  };
}

/** 台帳のリーグコードの日本語名。未知のコードはコードのまま出す（推測で埋めない） */
export function leagueLabel(code: string): string {
  return LEAGUE[code]?.[0] ?? code;
}
