/**
 * 日本語のチーム名 → 台帳の英語表記（football-data.co.uk / The Odds API）。
 *
 * 貼り付けられたハンデ表は日本語表記で来るが、台帳は英語表記で持っている。その橋渡し。
 * **表示用の読み替えであり、台帳・指紋には影響しない。**
 *
 * 値が配列なのは、同じクラブが台帳に複数の綴りで現れることがあるため
 * （例: "Machida" と "Machida Zelvia"）。解決は「その日の対象試合に実在する綴り」を選ぶ。
 *
 * ここに無い名前は**推測で埋めず**未解決として返す（フェイルクローズ）。
 * 出典はこのプロジェクトが 2026-09 に予想ページ用へ育てた表記表。
 */
export const JA_TO_EN: Readonly<Record<string, readonly string[]>> = {
  // 実際の貼り付けで出た別表記（2026-09-15 の実物から追加）
  "RCランス": ["Lens"],
  "マンチェスター・ユナイテッド": ["Man United"],
  "マンチェスター・シティ": ["Man City"],
  "エルフェアスベルク": ["Elversberg"],
  "バイエルン・ミュンヘン": ["Bayern Munich"],
  "サンジロワーズ": ["St. Gilloise"],
  "パリSG": ["Paris SG"],
  "インテル・ミラノ": ["Inter"],
  "ACミラン": ["Milan"],
  "レアル・ベティス": ["Betis"],
  "セビリア": ["Sevilla"],
  "アトレティコ": ["Ath Madrid"],
  "ビルバオ": ["Ath Bilbao"],
  "ADOデン・ハーグ": ["Den Haag"],
  "AZアルクマール": ["AZ Alkmaar"],
  "C大阪": ["Cerezo Osaka"],
  "FC東京": ["FC Tokyo"],
  "G大阪": ["Gamba Osaka"],
  "NECナイメヘン": ["Nijmegen"],
  "OHルーヴェン": ["Oud-Heverlee Leuven"],
  "PSV": ["PSV Eindhoven"],
  "アーセナル": ["Arsenal"],
  "アウクスブルク": ["Augsburg"],
  "アカデミコ・ヴィゼウ": ["Academico Viseu"],
  "アストン・ヴィラ": ["Aston Villa"],
  "アスレティック・ビルバオ": ["Ath Bilbao"],
  "アタランタ": ["Atalanta"],
  "アトレティコ・マドリード": ["Ath Madrid"],
  "アバディーン": ["Aberdeen"],
  "アヤックス": ["Ajax"],
  "アラベス": ["Alaves"],
  "アルヴェルカ": ["Alverca"],
  "アロウカ": ["Arouca"],
  "アンジェ": ["Angers"],
  "アンデルレヒト": ["Anderlecht"],
  "アントワープ": ["Antwerp"],
  "イプスウィッチ": ["Ipswich"],
  "インテル": ["Inter"],
  "ヴィレムII": ["Willem II"],
  "ウェステルロー": ["Westerlo"],
  "ウェストハム": ["West Ham"],
  "ヴェネツィア": ["Venezia"],
  "ウディネーゼ": ["Udinese"],
  "ウニオン・ベルリン": ["Union Berlin"],
  "ウルブス": ["Wolves"],
  "エクセルシオール": ["Excelsior"],
  "エストリル": ["Estoril"],
  "エストレラ・アマドーラ": ["Estrela"],
  "エスパニョール": ["Espanol"],
  "エバートン": ["Everton"],
  "エルチェ": ["Elche"],
  "エルフェルスベルク": ["Elversberg"],
  "オサスナ": ["Osasuna"],
  "オセール": ["Auxerre"],
  "カーザ・ピア": ["Casa Pia"],
  "カリアリ": ["Cagliari"],
  "カンブール": ["Cambuur"],
  "ギマランイス": ["Guimaraes"],
  "キルマーノック": ["Kilmarnock"],
  "クラブ・ブルッヘ": ["Club Brugge"],
  "クリスタル・パレス": ["Crystal Palace"],
  "ケルン": ["FC Koln"],
  "ゴー・アヘッド・イーグルス": ["Go Ahead Eagles"],
  "コベントリー": ["Coventry"],
  "コモ": ["Como"],
  "コルトレイク": ["Kortrijk"],
  "サッスオーロ": ["Sassuolo"],
  "サンタ・クララ": ["Santa Clara"],
  "サンダーランド": ["Sunderland"],
  "ジェノア": ["Genoa"],
  "シャルケ": ["Schalke 04"],
  "シャルルロワ": ["Charleroi"],
  "シュツットガルト": ["Stuttgart"],
  "ジル・ヴィセンテ": ["Gil Vicente"],
  "シント＝トロイデン": ["St Truiden"],
  "ズヴォレ": ["Zwolle"],
  "スタンダール": ["Standard"],
  "ストラスブール": ["Strasbourg"],
  "スパルタ・ロッテルダム": ["Sparta Rotterdam"],
  "スポルティング": ["Sp Lisbon"],
  "ズルテ・ワレヘム": ["Waregem"],
  "セビージャ": ["Sevilla"],
  "セルクル・ブルッヘ": ["Cercle Brugge"],
  "セルタ": ["Celta"],
  "セルティック": ["Celtic"],
  "セント・ジョンストン": ["St Johnstone"],
  "セント・ミレン": ["St Mirren"],
  "ダンディー": ["Dundee"],
  "ダンディー・ユナイテッド": ["Dundee United"],
  "チェルシー": ["Chelsea"],
  "デポルティボ": ["La Coruna"],
  "テルスター": ["Telstar"],
  "トゥールーズ": ["Toulouse"],
  "トゥエンテ": ["Twente"],
  "トッテナム": ["Tottenham"],
  "トリノ": ["Torino"],
  "ドルトムント": ["Dortmund"],
  "トロワ": ["Troyes"],
  "ナシオナル": ["Nacional"],
  "ナポリ": ["Napoli"],
  "ニース": ["Nice"],
  "ニューカッスル": ["Newcastle"],
  "ノッティンガム・フォレスト": ["Nott'm Forest"],
  "パーダーボルン": ["Paderborn"],
  "ハーツ": ["Hearts"],
  "バイエルン": ["Bayern Munich"],
  "ハイバーニアン": ["Hibernian"],
  "パリ・サンジェルマン": ["Paris SG"],
  "パリFC": ["Paris FC"],
  "ハル": ["Hull"],
  "バルセロナ": ["Barcelona"],
  "パルマ": ["Parma"],
  "バレンシア": ["Valencia"],
  "ハンブルガーSV": ["Hamburg"],
  "ビジャレアル": ["Villarreal"],
  "ファマリカン": ["Famalicao"],
  "フィオレンティーナ": ["Fiorentina"],
  "フェイエノールト": ["Feyenoord"],
  "フォルカーク": ["Falkirk"],
  "フォルトゥナ・シッタート": ["For Sittard"],
  "ブライトン": ["Brighton"],
  "フライブルク": ["Freiburg"],
  "ブラガ": ["Sp Braga"],
  "フラム": ["Fulham"],
  "フランクフルト": ["Ein Frankfurt"],
  "ブレーメン": ["Werder Bremen"],
  "ブレスト": ["Brest"],
  "ブレントフォード": ["Brentford"],
  "フローニンゲン": ["Groningen"],
  "フロジノーネ": ["Frosinone"],
  "ヘーレンフェーン": ["Heerenveen"],
  "ヘタフェ": ["Getafe"],
  "ベティス": ["Betis"],
  "ベフェレン": ["Beveren"],
  "ヘンク": ["Genk"],
  "ヘント": ["Gent"],
  "ベンフィカ": ["Benfica"],
  "ボーンマス": ["Bournemouth"],
  "ホッフェンハイム": ["Hoffenheim"],
  "ボルシアMG": ["M'gladbach"],
  "ポルト": ["Porto"],
  "ボローニャ": ["Bologna"],
  "マインツ": ["Mainz"],
  "マザーウェル": ["Motherwell"],
  "マラガ": ["Malaga"],
  "マリティモ": ["Maritimo"],
  "マルセイユ": ["Marseille"],
  "マンチェスター・C": ["Man City"],
  "マンチェスター・U": ["Man United"],
  "ミラン": ["Milan"],
  "メヘレン": ["Mechelen"],
  "モナコ": ["Monaco"],
  "モレイレンセ": ["Moreirense"],
  "モンツァ": ["Monza"],
  "ユトレヒト": ["Utrecht"],
  "ユニオン・サンジロワーズ": ["St. Gilloise"],
  "ユベントス": ["Juventus"],
  "ラ・ルヴィエール": ["RAAL La Louviere"],
  "ラージョ": ["Vallecano"],
  "ライプツィヒ": ["RB Leipzig"],
  "ラシン": ["Santander"],
  "ラツィオ": ["Lazio"],
  "ランス": ["Lens"],
  "リーズ": ["Leeds"],
  "リール": ["Lille"],
  "リオ・アヴェ": ["Rio Ave"],
  "リバプール": ["Liverpool"],
  "リヨン": ["Lyon"],
  "ル・アーヴル": ["Le Havre"],
  "ル・マン": ["Le Mans"],
  "レアル・ソシエダ": ["Sociedad"],
  "レアル・マドリード": ["Real Madrid"],
  "レッチェ": ["Lecce"],
  "レバークーゼン": ["Leverkusen"],
  "レバンテ": ["Levante"],
  "レンジャーズ": ["Rangers"],
  "レンヌ": ["Rennes"],
  "ローマ": ["Roma"],
  "ロリアン": ["Lorient"],
  "ロンメル": ["Lommel", "Lommel SK"],
  "浦和": ["Urawa Reds"],
  "横浜FM": ["Yokohama F. Marinos"],
  "岡山": ["Okayama"],
  "京都": ["Kyoto"],
  "広島": ["Sanfrecce Hiroshima"],
  "鹿島": ["Kashima Antlers"],
  "神戸": ["Vissel Kobe"],
  "水戸": ["Mito"],
  "清水": ["Shimizu S-Pulse"],
  "千葉": ["Chiba"],
  "川崎": ["Kawasaki Frontale"],
  "町田": ["Machida", "Machida Zelvia"],
  "長崎": ["V-Varen Nagasaki"],
  "東京V": ["Verdy"],
  "柏": ["Kashiwa Reysol", "Kashiwa"],
  "福岡": ["Avispa Fukuoka"],
  "名古屋": ["Nagoya Grampus"],
};

/** 英語表記 → 日本語（表示用）。同一クラブの別綴りはすべて同じ日本語へ落ちる */
export const EN_TO_JA: Readonly<Record<string, string>> = Object.fromEntries(
  Object.entries(JA_TO_EN).flatMap(([ja, ens]) => ens.map((en) => [en, ja])),
);

/** 全角・記号・空白の揺れを吸収する（表記そのものは書き換えない） */
export function normalizeTeamKey(name: string): string {
  return name
    .trim()
    .replace(/[\u3000\s]+/g, "")
    .replace(/[・･]/g, "")
    .replace(/[（(].*?[）)]/g, "")
    .replace(/[Ａ-Ｚａ-ｚ０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0));
}

const NORMALIZED: Map<string, readonly string[]> = new Map(
  Object.entries(JA_TO_EN).map(([ja, ens]) => [normalizeTeamKey(ja), ens]),
);

/**
 * 日本語名から台帳の英語表記の候補を返す。未知の名前は空配列（推測しない）。
 * 英語名がそのまま貼られた場合もそのまま通す。
 */
export function resolveTeamCandidates(name: string): readonly string[] {
  const raw = name.trim();
  if (!raw) return [];
  const direct = NORMALIZED.get(normalizeTeamKey(raw));
  if (direct) return direct;
  // 英語表記がそのまま貼られた場合
  if (EN_TO_JA[raw]) return [raw];
  return [];
}
